"""Application metadata for EBSD Scan Comparator packaging and distribution."""

APP_NAME = "EBSD Scan Comparator"
APP_SHORT_NAME = "EBSDScanComparator"
APP_ID = "{FB48909A-2AFD-4403-93F9-12A76104BE2E}"
APP_VERSION = "1.0.0"
APP_DESCRIPTION = "GUI for comparing EBSD scan maps and patterns."
APP_AUTHOR = "KikuchiBandAnalyzer contributors"
APP_PUBLISHER = "KikuchiBandAnalyzer"
APP_WEBSITE = "https://github.com/kvmani/kikuchiBandAnalyzer"
APP_COPYRIGHT = "Copyright (c) 2025 KikuchiBandAnalyzer contributors"
APP_LICENSE = "MIT"
APP_EXE_NAME = "EBSD_Scan_Comparator.exe"
APP_ICON_PATH = "assets/icons/ebsd_app.ico"
